# Generated by Django 3.1.3 on 2021-03-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='percent_change',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='price',
        ),
        migrations.AddField(
            model_name='asset',
            name='modified_buy_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='buy_price',
            field=models.FloatField(default=0),
        ),
    ]
