# Generated by Django 3.1.6 on 2021-04-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20210305_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='modified_buy_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
