# Generated by Django 3.1.6 on 2021-04-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20210413_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='growth',
            field=models.FloatField(default=0),
        ),
    ]
