# Generated by Django 3.1.6 on 2021-04-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_asset_growth'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
