# Generated by Django 3.1.6 on 2021-04-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_asset_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='cost',
            new_name='cost_after',
        ),
        migrations.AddField(
            model_name='asset',
            name='cost_before',
            field=models.FloatField(default=0),
        ),
    ]
